### ISSUE TITLE
[To-Do List] Tree Repository

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/CityPlans#10]
- [x] Create Tree Repository Portal at Hub
- [x] Upload tree files to here
- [x] Create Tree Repository world
- [x] Paste in trees 
- [x] Label pasted in Trees
